language: node_js
os:
  - linux
dist: trusty
sudo: true
addons:
  chrome: stable
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
script: npm run test

